### ISSUE TITLE
WoW 9.0 SetBackdrop error

### ISSUE THREAD

**Issue by Voxxel** [camas/EventScreenshot#1]
In 9.0:

`1x EventScreenshot\EventScreenshot-0.2.1.lua:22: attempt to call method 'SetBackdrop' (a nil value)
[string "@EventScreenshot\EventScreenshot-0.2.1.lua"]:22: in function <EventScreenshot\EventScreenshot.lua:10>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>`

**Comment by camas** [comment]
Cheers

Fixed in 3bb651b8

0.2.2 available on Curse whenever it gets approved
